location                = "eastus"  # OpenAI quota available: eastus, swedencentral, australiaeast
env                     = "dev"
prefix                  = "sk"
openai_sku              = "S0"
gpt_model               = "gpt-4o"
gpt_model_version       = "2024-08-06"
gpt_capacity            = 10          # 10K TPM
embedding_model         = "text-embedding-ada-002"
embedding_model_version = "2"
embedding_capacity      = 60          # 60K TPM
search_sku              = "basic"
